name: Deploy to staging
on:
    push:
        branches:
        - staging
    workflow_dispatch:
        branches:
        - staging
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js dependencies
              run: yarn

            - name: Run ESLint
              run: yarn lint
